### ISSUE TITLE
Docker failure to build gil-goblin-database

### ISSUE THREAD

**Issue by flae5251** [NickReinlein/GilGoblin#192]
Hi, trying to build the current version of the code and I'm having a similar issue to one that has been closed a few months ago.

After running `docker-compose up -d` from cmd, frontend container runs with no issue, meanwhile the remaining 4 are stuck in a constant running/restarting loop. I've tracked the issue might be the fact that when running `database` first, I get the error message:

`mkdir: can't create directory '': No such file or directory`

Other containers give the first error message:

`Unhandled exception. System.Exception: Failed to get connection string`

that I suspect may be due to database's fail, since I noticed other containers depend on it. 

I've tried running as admin to ensure it's not a permission issue, but it didn't change anything. Any ideas?

**Comment by NickReinlein** [comment]
Hi flae5251,
Sorry for the late reply; I was on holiday and am only seeing this question now. I know the root cause. I didn't realize I had stored the connection strings in my local `.env` file without mentioning it clearly anywhere.

I just merged a [pull request](https://github.com/NickReinlein/GilGoblin/pull/193) that may help solve the issue.
- Please take a look at the new `.env.example`. You can use it to create a new `.env` file, and optionally change the password.
- Additionally, I made a tiny change for the `Dockerfile` that may help. I don't have the same issue on Linux Ubuntu.

 
Let me know if this helps.

**Comment by flae5251** [comment]
Thank you for your reply!

I had to specify the .env file from docker-compose command, but otherwise now the variables load fine. However, another issue appeared: while other 4 containers run correctly, gilgoblin-accountant is still refreshing and the site from the frontend is not getting populated with any database contents. I can't even choose the world to check for prices.

I caught three messages. From -database:

`LOG:  could not receive data from client: Connection reset by peer`

From -accountant (redacted the IP address):

`Unhandled exception. System.IO.IOException: Failed to bind to address [127.0.... IP address here] address already in use.`

And a bunch of these from -dataupdater:

```
Exception data:

          Severity: ERROR

          SqlState: 23503

          MessageText: insert or update on table "recent_purchase" violates foreign key constraint "recent_purchase_item_id_fkey"

```
What could be the cause? Do I need to change something I overlooked? I also tried running the code on linux, and while the images build without an issue and the databases seem to be uploaded, the site still doesn't show any data.

Apologies if these are stupid questions, I never used docker (only other environments) or SQL, and my knowledge about systems used in the code is very limited.

**Comment by flae5251** [comment]
Thanks again for the reply.

I tried deleting existing images with the command and the result is the same. The databases seemed to be downloading after `docker compose --env-file file.env up -d` but the errors I mentioned before are still appearing and the frontend site is not populated with data.

I'm not sure how to check whether it did bind a port on Linux; I am able to access the frontend site, but again without data. Sorry once again - I'm not familiar with networks and ports, as I work in a different field!

More info about errors:

For -database, I get errors that look like these:

`2025-08-04 07:55:15.244 UTC [124] LOG:  could not send data to client: Connection reset by peer

2025-08-04 07:55:15.244 UTC [124] STATEMENT:  SELECT r.id, r.amount, r.is_hq, r.last_updated, r.recipe_id, r.world_id

	FROM recipe_cost AS r

	WHERE r.world_id = $1

2025-08-04 07:55:15.244 UTC [124] FATAL:  connection to client lost`

From -accountant:

`info: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider[1]

      No action descriptors found. This may indicate an incorrectly configured application or missing application parts. To learn more, visit [https://aka.ms/aspnet/mvc/app-parts⁠](https://aka.ms/aspnet/mvc/app-parts)

warn: Microsoft.AspNetCore.Server.Kestrel[0]

      Overriding address(es) http://*:8080. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.

fail: Microsoft.Extensions.Hosting.Internal.Host[11]

      Hosting failed to start

      System.IO.IOException: Failed to bind to address http://127.0.0.1:55450/ address already in use.`

**Comment by NickReinlein** [comment]
Hi flae,
Sorry for the late answer. I did try it out myself. I was able to run this locally and in production to ensure it works. I did push a small change in Docker. You should be able to update your Docker images with the command `docker compose pull` (and then `docker compose up -d` as usual)

1. Please ignore `uld not send data to client: Connection reset by peer` -> I get this too and it still "works" for me. I will eventually look into this bug but it doesn't prevent the database, API, or frontend from working
2. Ignore the accountant for now. It will calculate costs & profits based on the database entries, but for now let's make sure everything is hooked up with stale data available
3. The frontend seems functional. Does the API work? Do you see any errors? Did it bind to a port?
4. Do you have a way to check if the database exists and is populated? Using a tool like Datagrip or Dbeaver, can you access the Postgres database? It should be available and accessible with the same credentials you have in your environment variables 

Based on your reply, we can take see what the next steps are

**Comment by NickReinlein** [comment]
Hi flae,

Bad news: There was a bug in the mapping of the port and url from frontend to backend
Good news: Fixed it with #195 

Can you please do the `docker compose pull` command and try again? Does it work this time?

**Comment by NickReinlein** [comment]
Hi flae,
Feel free to re-open an issue if something doesn't work but I tried again locally and it works for me.

Closing this issue for now.
